### ISSUE TITLE
compile error: undefined: pageSize

### ISSUE THREAD

**Issue by Fedsd1** [yoursunny/ndpresponder#1]
```shell
$ go install github.com/yoursunny/ndpresponder@main
go: downloading github.com/yoursunny/ndpresponder v0.0.0-20230624195751-4500a2591d01
go: downloading github.com/urfave/cli/v2 v2.25.7
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/fsouza/go-dockerclient v1.9.7
go: downloading github.com/vishvananda/netlink v1.2.1-beta.2
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/net v0.11.0
go: downloading golang.org/x/sys v0.9.0
go: downloading inet.af/netaddr v0.0.0-20230525184311-b8eac61e914a
go: downloading github.com/docker/docker v24.0.2+incompatible
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/moby/patternmatcher v0.5.0
go: downloading github.com/vishvananda/netns v0.0.4
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading go.uber.org/atomic v1.11.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading go4.org/intern v0.0.0-20230525184215-6c62f75575cb
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/opencontainers/image-spec v1.1.0-rc3
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/containerd/containerd v1.7.2
go: downloading github.com/klauspost/compress v1.16.6
go: downloading github.com/moby/sys/sequential v0.5.0
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/moby/term v0.5.0
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/opencontainers/runc v1.1.7
go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20230525183740-e7c30c78aeb2
go: downloading github.com/opencontainers/go-digest v1.0.0
# github.com/google/gopacket/afpacket
go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket/options.go:176:19: undefined: pageSize
go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket/options.go:177:85: undefined: pageSize
```

**Comment by yoursunny** [comment]
Please paste error messages in textual format, not as pictures.

**Comment by RDReindeer** [comment]
go: downloading github.com/yoursunny/ndpresponder v0.0.0-20230624195751-4500a2591d01
go: downloading github.com/urfave/cli/v2 v2.25.7
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/fsouza/go-dockerclient v1.9.7
go: downloading github.com/vishvananda/netlink v1.2.1-beta.2
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/net v0.11.0
go: downloading golang.org/x/sys v0.9.0
go: downloading inet.af/netaddr v0.0.0-20230525184311-b8eac61e914a
go: downloading github.com/docker/docker v24.0.2+incompatible
go: downloading github.com/docker/go-units v0.5.0
go: downloading github.com/moby/patternmatcher v0.5.0
go: downloading github.com/vishvananda/netns v0.0.4
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading go.uber.org/atomic v1.11.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading go4.org/intern v0.0.0-20230525184215-6c62f75575cb
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/opencontainers/image-spec v1.1.0-rc3
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/containerd/containerd v1.7.2
go: downloading github.com/klauspost/compress v1.16.6
go: downloading github.com/moby/sys/sequential v0.5.0
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/moby/term v0.5.0
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/opencontainers/runc v1.1.7
go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20230525183740-e7c30c78aeb2
go: downloading github.com/opencontainers/go-digest v1.0.0
# github.com/google/gopacket/afpacket
go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket/options.go:176:19: undefined: pageSize
go/pkg/mod/github.com/google/gopacket@v1.1.19/afpacket/options.go:177:85: undefined: pageSize

**Comment by Fedsd1** [comment]
> Please paste error messages in textual format, not as pictures.

OK,i try to compile on my vps and pc,but appear same error

**Comment by yoursunny** [comment]
> undefined: pageSize

This error is likely what happens when the system lacks a C compiler or Cgo is otherwise disabled.
You can resolve this by installing a C compiler.
In Debian/Ubuntu it's `sudo apt install build-essential` .
